letter_name_sys:
  # Top Row
  # -------------------------------------------------------
  - "C1"  # <-- KeyOrder[0]
  - "D1"  # <-- KeyOrder[1]
  - "E1"  # <-- KeyOrder[2]
  - "F1"  # <-- KeyOrder[3]
  - "G1"  # <-- KeyOrder[4]

  # Middle Row
  # -------------------------------------------------------
  - "A1"  # <-- KeyOrder[5]
  - "B1"  # <-- KeyOrder[6]
  - "C2"  # <-- KeyOrder[7]
  - "D2"  # <-- KeyOrder[8]
  - "E2"  # <-- KeyOrder[9]

  # Bottom Row
  # -------------------------------------------------------
  - "F2"  # <-- KeyOrder[10]
  - "G2"  # <-- KeyOrder[11]
  - "A2"  # <-- KeyOrder[12]
  - "B2"  # <-- KeyOrder[13]
  - "C3"  # <-- KeyOrder[14]

abc_name_sys:
  # Top Row
  # -------------------------------------------------------
  - "A1"  # <-- KeyOrder[0]
  - "A2"  # <-- KeyOrder[1]
  - "A3"  # <-- KeyOrder[2]
  - "A4"  # <-- KeyOrder[3]
  - "A5"  # <-- KeyOrder[4]

  # Middle Row
  # -------------------------------------------------------
  - "B1"  # <-- KeyOrder[5]
  - "B2"  # <-- KeyOrder[6]
  - "B3"  # <-- KeyOrder[7]
  - "B4"  # <-- KeyOrder[8]
  - "B5"  # <-- KeyOrder[9]

  # Bottom Row
  # -------------------------------------------------------
  - "C1"  # <-- KeyOrder[10]
  - "C2"  # <-- KeyOrder[11]
  - "C3"  # <-- KeyOrder[12]
  - "C4"  # <-- KeyOrder[13]
  - "C5"  # <-- KeyOrder[14]

number_name_sys:
  # Top Row
  # -------------------------------------------------------
  - "1"  # <-- KeyOrder[0]
  - "2"  # <-- KeyOrder[1]
  - "3"  # <-- KeyOrder[2]
  - "4"  # <-- KeyOrder[3]
  - "5"  # <-- KeyOrder[4]

  # Middle Row
  # -------------------------------------------------------
  - "6"  # <-- KeyOrder[5]
  - "7"  # <-- KeyOrder[6]
  - "8"  # <-- KeyOrder[7]
  - "9"  # <-- KeyOrder[8]
  - "10"  # <-- KeyOrder[9]

  # Bottom Row
  # -------------------------------------------------------
  - "11"  # <-- KeyOrder[10]
  - "12"  # <-- KeyOrder[11]
  - "13"  # <-- KeyOrder[12]
  - "14"  # <-- KeyOrder[13]
  - "15"  # <-- KeyOrder[14]

solfege_name_sys:
  # Top Row
  # -------------------------------------------------------
  - "Do1"  # <-- KeyOrder[0]
  - "Re1"  # <-- KeyOrder[1]
  - "Mi1"  # <-- KeyOrder[2]
  - "Fa1"  # <-- KeyOrder[3]
  - "Sol1"  # <-- KeyOrder[4]

  # Middle Row
  # -------------------------------------------------------
  - "La1"  # <-- KeyOrder[5]
  - "Ti1"  # <-- KeyOrder[6]
  - "Do2"  # <-- KeyOrder[7]
  - "Re2"  # <-- KeyOrder[8]
  - "Mi2"  # <-- KeyOrder[9]

  # Bottom Row
  # -------------------------------------------------------
  - "Fa2"  # <-- KeyOrder[10]
  - "Sol2"  # <-- KeyOrder[11]
  - "La2"  # <-- KeyOrder[12]
  - "Ti2"  # <-- KeyOrder[13]
  - "Do3"  # <-- KeyOrder[14]

chromatic_name_sys:
  # Top Row
  # -------------------------------------------------------
  - "C"  # <-- KeyOrder[0]
  - "C#"  # <-- KeyOrder[1]
  - "D"  # <-- KeyOrder[2]
  - "D#"  # <-- KeyOrder[3]
  - "E"  # <-- KeyOrder[4]

  # Middle Row
  # -------------------------------------------------------
  - "F"  # <-- KeyOrder[5]
  - "F#"  # <-- KeyOrder[6]
  - "G"  # <-- KeyOrder[7]
  - "G#"  # <-- KeyOrder[8]
  - "A"  # <-- KeyOrder[9]

  # Bottom Row
  # -------------------------------------------------------
  - "A#"  # <-- KeyOrder[10]
  - "B"  # <-- KeyOrder[11]
  - "C2"  # <-- KeyOrder[12]
  - "C#2"  # <-- KeyOrder[13]
  - "D2"  # <-- KeyOrder[14]
